### ISSUE TITLE
Associate circuit diagrams w/ .ino files?

### ISSUE THREAD

**Issue by bchartoff** [sbma44/arduino_class#3]
For now, it's easy enough to recreate circuits from lessons one and two, but I can see eventually how a .ino file (plus assoc .py or whatever) won't be useable without an associated circuit diagram jpg (or whatever).

I can see this being useful if we-the-students want to post our own code/ projects &mdash; I'd love to see what classmates are working on (@jcarbaugh 's cymk thing, for example), this is kinda a separate issue but mentioning it here since it's related (I'll make a pull request w/ my morse code code in /student-projects/lesson-2 or somewhere when I'm home on my own laptop tonight). For more complex projects, we might want to upload circuit diagrams w/ our code.

Best practices in the arduino community for circuit diagrams? Specifically, is there software that simplifies the sketching process?

**Comment by konklone** [comment]
oooh yes, please make us collaborators, we can make a `students/` folder and upload our work there. =)

**Comment by stvnrlly** [comment]
I would definitely use a `students/` folder. In addition to seeing other projects, it would also be useful to see how other people solved the same problem (for example, the prompts at the end of Lesson 2).

**Comment by sbma44** [comment]
OK! You're all added. Please do as you see fit.

On sharing hardware: here the news is not as great. The diagrams you've seen me make have been created with [Fritzing](http://fritzing.org). This is a nice visual tool and might suffice for these purposes. I have also used iCircuit a bit, though it's not really designed for Arduino.

However, the point of drawing circuit diagrams in digital formats rapidly becomes about the construction of printed circuit boards (PCBs). And for that you will need more sophisticated software. There is not a ton of point to Fritzing right now unless you are teaching a class and need nice slides, IMO. Again, it might be the best tool for right now.

But ultimately you will want to use CadSoft EAGLE, which is the gold standard and offers a freeware version but requires X Windows ([Sparkfun has a series of tutorials about it](https://www.sparkfun.com/tutorials/108)). Or the Linux suite built around the `pcb` tool. Or perhaps [Razen](http://razencad.com/) which I haven't used but am excited about. 

That's the lay of the land as I currently understand it. There might be more awesome stuff out there, but right now the simple tools are ones you'll definitely outgrow and the complex ones have a steep learning curve. I think I would recommend Fritzing for now.

**Comment by sbma44** [comment]
Hmm googling around it seems like people _are_ using Fritzing for PCB production. Maybe it's worth another look.

**Comment by kathykiely** [comment]
Add me too! kathykiely

**Comment by LindsayYoung** [comment]
LindsayYoung

**Comment by sbma44** [comment]
@LindsayYoung @kathykiely roger! You're both added.

**Comment by LindsayYoung** [comment]
Thanks!

Lindsay Young
Sunlight Foundation http://www.sunlightfoundation.com/

**Comment by kathykiely** [comment]
I feel like I've just been invited to the cool kids table.

On Thu, Jun 12, 2014 at 10:39 AM, LindsayYoung notifications@github.com
wrote:

> Thanks!
> 
> Lindsay Young
> Sunlight Foundation http://www.sunlightfoundation.com/
> 
> On Thu, Jun 12, 2014 at 10:30 AM, Tom Lee notifications@github.com
> wrote:
> 
> > @LindsayYoung https://github.com/LindsayYoung @kathykiely
> > https://github.com/kathykiely roger! You're both added.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/sbma44/arduino-class/issues/3#issuecomment-45898566.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sbma44/arduino-class/issues/3#issuecomment-45899926.

## 

Kathy Kiely
202-256-4748 (cell)

**Comment by LindsayYoung** [comment]
You are a cool kid, @kathykiely https://github.com/kathykiely

Lindsay Young
Sunlight Foundation http://www.sunlightfoundation.com/

**Comment by mwweinberg** [comment]
please add me too
